name: paper_v4
repeat_action_probability: 0.0
frameskip: 1
action_repeat: 4
full_action_space: false
noop_max: 30
terminal_on_life_loss_train: true
terminal_on_life_loss_eval: false
eval_max_episode_frames: 18000
