name: dqn
network: nature
double: false
gamma: 0.99
frame_stack: 4
update_frequency: 4
target_update_freq: 10000
replay_start_size: 50000
batch_size: 32
max_grad_norm: null
n_step: 1
use_c51: false
num_atoms: 51
v_min: -10.0
v_max: 10.0
